# nixpacks.toml  ─ ship a static, glibc-independent FFmpeg
[phases.setup]
cmds = [
  # 1) download   2) untar   3) symlink into PATH
  "curl -L -o /tmp/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz",
  "mkdir -p /opt/ffmpeg && tar -xJf /tmp/ffmpeg.tar.xz -C /opt/ffmpeg --strip-components=1",
  "ln -sf /opt/ffmpeg/ffmpeg /usr/local/bin/ffmpeg"
]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
